
services:
  shard1_primary:
    image: mongo:7.0
    container_name: shard1_primary
    hostname: shard1_primary
    command: ["mongod", "--replSet", "rs_shard1", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27101:27017"
    volumes:
      - shard1_primary_data:/data/db
    networks:
      - mongo_sharded_net

  shard1_secondary:
    image: mongo:7.0
    container_name: shard1_secondary
    hostname: shard1_secondary
    command: ["mongod", "--replSet", "rs_shard1", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27102:27017"
    volumes:
      - shard1_secondary_data:/data/db
    networks:
      - mongo_sharded_net

  shard1_arbiter:
    image: mongo:7.0
    container_name: shard1_arbiter
    hostname: shard1_arbiter
    command: ["mongod", "--replSet", "rs_shard1", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27103:27017"
    volumes:
      - shard1_arbiter_data:/data/db
    networks:
      - mongo_sharded_net

  shard2_primary:
    image: mongo:7.0
    container_name: shard2_primary
    hostname: shard2_primary
    command: ["mongod", "--replSet", "rs_shard2", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27201:27017"
    volumes:
      - shard2_primary_data:/data/db
    networks:
      - mongo_sharded_net

  shard2_secondary:
    image: mongo:7.0
    container_name: shard2_secondary
    hostname: shard2_secondary
    command: ["mongod", "--replSet", "rs_shard2", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27202:27017"
    volumes:
      - shard2_secondary_data:/data/db
    networks:
      - mongo_sharded_net

  shard2_arbiter:
    image: mongo:7.0
    container_name: shard2_arbiter
    hostname: shard2_arbiter
    command: ["mongod", "--replSet", "rs_shard2", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27203:27017"
    volumes:
      - shard2_arbiter_data:/data/db
    networks:
      - mongo_sharded_net

  shard3_primary:
    image: mongo:7.0
    container_name: shard3_primary
    hostname: shard3_primary
    command: ["mongod", "--replSet", "rs_shard3", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27301:27017"
    volumes:
      - shard3_primary_data:/data/db
    networks:
      - mongo_sharded_net

  shard3_secondary:
    image: mongo:7.0
    container_name: shard3_secondary
    hostname: shard3_secondary
    command: ["mongod", "--replSet", "rs_shard3", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27302:27017"
    volumes:
      - shard3_secondary_data:/data/db
    networks:
      - mongo_sharded_net

  shard3_arbiter:
    image: mongo:7.0
    container_name: shard3_arbiter
    hostname: shard3_arbiter
    command: ["mongod", "--replSet", "rs_shard3", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27303:27017"
    volumes:
      - shard3_arbiter_data:/data/db
    networks:
      - mongo_sharded_net
  router1:
    build:
      context: ./routers/router1
    container_name: router1
    hostname: router1
    ports:
      - "3001:3000"
    networks:
      - mongo_sharded_net
  router2:
    build:
      context: ./routers/router2
    container_name: router2
    hostname: router2
    ports:
      - "3002:3000"
    networks:
      - mongo_sharded_net

  load_balancer:
    build:
      context: ./load-balancer
    container_name: load_balancer
    hostname: load_balancer
    depends_on:
      - router1
      - router2
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - mongo_sharded_net 

volumes:
  shard1_primary_data:
  shard1_secondary_data:
  shard1_arbiter_data:
  shard2_primary_data:
  shard2_secondary_data:
  shard2_arbiter_data:
  shard3_primary_data:
  shard3_secondary_data:
  shard3_arbiter_data:

networks:
  mongo_sharded_net:
    driver: bridge